### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by ashalkhakov** [githwxi/ATS-Xanadu#1]
I thinks this merits attention.

How do we setup CI such that all tests run on every commit?

**Comment by githwxi** [comment]
Hi Artyom,

I haven't got to CI setup yet. Will certainly do this after making more progress.

**Comment by ashalkhakov** [comment]
Hi Hongwei,

Yes, I'll look into this issue on the weekend!

**Comment by ashalkhakov** [comment]
Could you please assign me? Or actually, I think you should really move this repository to an organization and assign some team members.

**Comment by githwxi** [comment]
Yes, an organization is planned later for ATS/Xanadu.

ATS3 is still an idea and there is likely a lot of experimentation needed. At the first stage, I would like to provide other developers with a library (libatsxopt) (if they use ATS2) and some ways to generate JSON for various internal abstract syntax trees (if they use other languages for their implementation).

**Comment by ashalkhakov** [comment]
I think this issue can be considered done with. I'll add a separate issue about packaging releases.
