### ISSUE TITLE
Parsing implementation declarations

### ISSUE THREAD

**Issue by sparverius** [githwxi/ATS-Xanadu#15]
The parser for implementation declarations (D0Cimpdecl, [ptok_impdecl](https://github.com/githwxi/ATS-Xanadu/blob/4961bd9b64a9748d9e8f6ac3d67ea595c4ba2b16/srcgen/xats/DATS/parsing_dynexp.dats#L3063)) seems to suggest that the following is valid,

```ats
impltmp {a}<b> ident (funargs) = ... 
```
#### First question:
What is the reason for parsing both `{...}` and the new syntax for function templates `<...>` 
[here](https://github.com/githwxi/ATS-Xanadu/blob/4961bd9b64a9748d9e8f6ac3d67ea595c4ba2b16/srcgen/xats/DATS/parsing_dynexp.dats#L3082-L3085)?

#### Second question:

One can write an expression such as,
```ats
impltmp(a:tflt) foo<container(a)>(...) = ... 
```
Will this syntax be supported in ATS3?

**Comment by githwxi** [comment]
First:

impltmp{a:type}<b> is accepted by the parser but should be rejected by synread.

Second:

It should be written as:

```
impltmp{a:tflt} foo<container<a>(...)
```

**Comment by sparverius** [comment]
Thanks!
